### ISSUE TITLE
Hello you need Help to improve this project ?

### ISSUE THREAD

**Issue by brunohorta82** [dzurikmiroslav/esp32-evse#3]
Hello, I am working on one similar project, if you want we can't join energies and make a super evse based on ESP32 :).
Please let me know if you are interested.
my email: brunohorta82@gmail.com

**Comment by dzurikmiroslav** [comment]
Hi, YES, it will be great, but unfortunately now this is one-man-show project :-) 
I need to write some documentation and guides...

**Comment by vitalyxxl** [comment]
Problem with install project at my computer ......
( not found  files  at project dirs ) 
Please help me  continue !!!

**Comment by dzurikmiroslav** [comment]
After checkout repository, did you fetch git submodules? 
`git submodule update --init`

**Comment by vitalyxxl** [comment]
Hello friend ! You reply -  good !
Please , give me your email for best communication . If possible
Best regards !






вс, 22 янв. 2023 г. в 00:23, Miroslav Dzúrik ***@***.***>:

**Comment by vitalyxxl** [comment]
Installation does not go through GIT. An error is generated:
   error: invalid path 'components/peripherals/include/aux.h'  

I tried to install by downloading the ZIP archive and extracting it to the specified folder . 

My next step ?

**Comment by dzurikmiroslav** [comment]
I suggest you to clone project by git:
*git clone https://github.com/dzurikmiroslav/esp32-evse.git
<https://github.com/dzurikmiroslav/esp32-evse.git>*
After clone, init git submodules:
*git submodule update --init*

Otherwise you must manually download and place submodules by .gitmodules
config file...

For build you need ESP-IDF v5.0 (
https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32/get-started/index.html
)



ne 22. 1. 2023 o 11:35 vitalyxxl ***@***.***> napísal(a):

**Comment by dzurikmiroslav** [comment]
Hi
I am developing this project on Ubuntu OS, I found out that "aux" file name
is not allowed on Windows :-)
I was renamed to "aux_io".



po 23. 1. 2023 o 22:04 vitalyxxl ***@***.***> napísal(a):

**Comment by vitalyxxl** [comment]
Thanks for the correction ! 
Now the project install without errors and warnings.
Compilation and assembly   ( idf.py build)   goes without errors (there are a few warnings, but I think this is not critical .....)
Binary files are written    ( idf.py flash )      to the controller without any remarks. 100% ready.

When I reboot the board, I see the following entries in the monitor  ( idf.py monitor )  :

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clockdiv:2
load:0x3fff0030,len:7000
load:0x40078000,len:15356
ho 0 tail 12 room 4
**load:0x40080400,len:3824
0x40080400: _init at ??:?**

**entry 0x40080648**

-------------------------------------------------------------------------------------------------

Is this normal behavior?

No access point is found in the list of Wifi networks ..... I have no idea how to connect to the server EVSE :( ......
How can I proceed further to revive :) ?

**Comment by dzurikmiroslav** [comment]
If that log was printed once It's good, if repeating continuously there is
some problem...
When you press button on gpio pin, who you defined in board.cfg
BUTTION_WIFI_GPIO
device should create WiFi AP with name esve-XXXXXX, after connect on it, go
to ip 192.168.4.1 there should be WebUI



ut 24. 1. 2023 o 21:15 vitalyxxl ***@***.***> napísal(a):

**Comment by vitalyxxl** [comment]
Thanks for the prompt response.
I made all the necessary settings related to the numbers of inputs and outputs ( LEDS/BUTTONS ...) for the ESP32  dev board.
There were no changes in the behavior of the board .... 
Experiments on other ESP32 dev boards  showed the same behavior. That is, there are no obvious signs that the loaded code is working correctly.
If anyone can give me a ready-made dump or files for controller firmware, 
I would be grateful. In general, has anyone managed to create a working project from this repository in the Windows 10 (64) environment. 
Maybe I'm not digging there? Although other projects are successfully assembled and quite efficient ....

Thanks to all who responded.

**Comment by dzurikmiroslav** [comment]
Before compile & flash project, did you set right ESP-IDF configuration?
To deploy board config must be set `CONFIG_BOARD_CONFIG_DEPLOY=y` and `CONFIG_BOARD_CONFIG="custom"`.
While flashing, will be deployed board config from `cfg/custom/board.cfg`, you can edit it before flashing...
https://github.com/dzurikmiroslav/esp32-evse/wiki/Board-config

**Comment by vitalyxxl** [comment]
Thanks for the clarification. But I made changes (just in case) to all three configuration files ..... It still didn’t work .....
But I'll check again. Apparently not today.

By the way, in my chargers based on I use 12V power at the input of the board (as in the original version). 
And I get negative  voltage (-12) volts using a specialized chip TC 1044 (TC 7660 ....).
I like this solution due to its low price ($0.3 -0.8 compared to the converter as in the original project), 
small dimensions and a minimum number of additional "strapping" components .... only two capacitors !

Why wouldn't the author of this project use this solution? 

Yes, there is a reworking of the scheme, but it's worth it! I'll take care of it anyway. 
The main thing is to somehow launch the project in its current form ......

Another question about the dimensions of the printed circuit board.
In my opinion, it is more logical to use the dimensions for installation in DIN RAIL cases . 
Then it will also be possible to place a small-sized power supply (and in the future, a LCD display (?) on the top cover) in one case. I'm sure this will be very true in terms of creating finished devices. 
It remains to add only a power contactor (relay) in common wall-box.

Do you think this proposal deserves consideration ? :)

PS: Is there another way to communicate with the author of the project? For example , email ? :)

**Comment by dzurikmiroslav** [comment]
Many topics in last comment :) 
Please start separate discussions in https://github.com/dzurikmiroslav/esp32-evse/discussions
I'd like to talk about HW design with you...
